#
# Module manifest for module 'CliStyler'
#
# Generated by: alain
#
# Generated on: 8/23/2023
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'CliStyler.psm1'
    # Version number of this module.
    ModuleVersion         = '<ModuleVersion>'
        # ID used to uniquely identify this module
    GUID = 'c9de42b3-1536-429d-8aef-3e861e9b9eb0'

    # Author of this module
    Author = 'alain'

    # Company or vendor of this module
    CompanyName = 'alainQtec'

    # Copyright statement for this module
    Copyright             = "Alain Herve (c) <Year>. All rights reserved."

    # Description of the functionality provided by this module
    Description = 'A Module for configuring and customizing their command-line environments'

    PowerShellVersion     = '3.0'
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''
    CLRVersion            = '2.0.50727'
    ProcessorArchitecture = 'None'
    RequiredModules       = @()
    RequiredAssemblies    = @()
    ScriptsToProcess      = @()
    TypesToProcess        = @()
    FormatsToProcess      = @()
    NestedModules         = @()
    FunctionsToExport     = @(
        '<FunctionsToExport>'
    )
    CmdletsToExport       = '*'
    VariablesToExport     = '*'
    AliasesToExport       = '*'
    # DSC resources to export from this module
    # DscResourcesToExport = @()
    # List of all modules packaged with this module
    # ModuleList = @()
    # List of all files packaged with this module
    # FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData           = @{
    PSData = @{
        Tags         = @('Cli', 'Terminal', 'style')
        LicenseUri   = 'https://github.com/alainQtec/CliStyler/blob/main/LICENSE'
        ProjectUri   = 'https://github.com/alainQtec/CliStyler'

        # A URL to an icon representing this module.
        # IconUri = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()
        ReleaseNotes = "
<ReleaseNotes>
"
        } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
 HelpInfoURI           = 'https://github.com/alainQtec/CliStyler/Wiki'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

